
#spring.devtools.restart.enabled: true

##spring.devtools.restart.additional-paths: src/main/java

#spring.devtools.restart.exclude: WEB-INF/**

#logging.pattern.console = %d - %msg%n
#logging.path = /var/log/tomcat/
#logging.file=/var/log/tomcat/sell.log
#logging.level.com.imooc.SellApplicationTests=debug
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password:
      url: jdbc:mysql://127.0.0.1:3306/sell?useUnicode=true&characterEncoding=utf8
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.0.113
    port: 6379

server:
  context-path: /sell

wechat:
  mpAppId:  wxd898fcb01713c658
  mpAppSecret:  6c43a48dd8a105968007c500a5492a87
  openAppId: wx6ad144e54af67d87
  openAppSecret: 6c43a48dd8a105968007c500a5492a87
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sellxili.natapp1.cc/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://sellxili.natapp1.cc
  wechatOpenAuthorize: http://sellxili.natapp1.cc
  sell: http://127.0.0.1:8080
logging:
  level:
    com.imooc.dataobject.mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml

